
VIEW_WIDGET_WIDTH = {
    'ID': 50,
    'ACCOUNT_GROUP_ALIAS': 30,
    'ACCOUNT_TYPE_NAME': 50,
    'ACCOUNT_TYPE_NORMAL_SIDE': 10,
    'ACCOUNT_NAME': 30,
    'ACCOUNT_ALIAS': 50,
    'CURRENCY_CODE': 5,
    'OVERDRAFT_LIMIT': 20,
    'PROVIDER_NAME': 30,
    'DESCRIPTION': 30,
    'TIMESTAMP': 20,
}

TABLE_COLUMN_WIDTH = {
    'ID': 50,
    'ACCOUNT_TYPE_NAME': 200,
    'ACCOUNT_TYPE_NORMAL_SIDE': 80,
    'ACCOUNT_NAME': 200,
    'ACCOUNT_DESCRIPTION': 200,
    'ACCOUNT_NUMBER': 200,
    'MONEY': 100,
    'TIMESTAMP': 120,
    'CURRENCY_CODE': 60,
    'DESCRIPTION': 200,
    'PROVIDER_NAME': 200,
}